In [8]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [9]:
dataset = pd.read_csv('Galtons Height Data.csv  ')
x = dataset.iloc[:,1:-2].values
y = dataset.iloc[:, -2].values

In [10]:
x  #Values of independent variables in the data set

array([[78.5, 67.0, 'M'],
       [78.5, 67.0, 'F'],
       [78.5, 67.0, 'F'],
       ...,
       [68.5, 65.0, 'F'],
       [68.5, 65.0, 'F'],
       [68.5, 65.0, 'F']], dtype=object)

In [11]:
y  #Value of dependent variable in the data set

array([73.2, 69.2, 69. , 69. , 73.5, 72.5, 65.5, 65.5, 71. , 68. , 70.5,
       68.5, 67. , 64.5, 63. , 72. , 69. , 68. , 66.5, 62.5, 62.5, 69.5,
       76.5, 74. , 73. , 73. , 70.5, 64. , 70.5, 68. , 66. , 66. , 65.5,
       74. , 70. , 68. , 67. , 67. , 66. , 63.5, 63. , 65. , 68. , 67. ,
       71. , 70.5, 66.7, 72. , 70.5, 70.2, 70.2, 69.2, 68.7, 66.5, 64.5,
       63.5, 74. , 73. , 71.5, 62.5, 66.5, 62.3, 66. , 64.5, 64. , 62.7,
       73.2, 73. , 72.7, 70. , 69. , 68.5, 68. , 66. , 73. , 68.5, 68. ,
       73. , 71. , 67. , 74.2, 70.5, 69.5, 66. , 65.5, 65. , 65. , 65.5,
       66. , 63. , 70.5, 70.5, 69. , 65. , 63. , 69. , 67. , 63. , 73. ,
       67. , 70.5, 70. , 66.5, 63. , 67.5, 67.2, 66.7, 64. , 71. , 70. ,
       70. , 66. , 65. , 65. , 74. , 72. , 69. , 67.5, 63.5, 72. , 71.5,
       71.5, 70. , 68. , 65.7, 78. , 74. , 73. , 72. , 67. , 73.2, 73. ,
       69. , 67. , 70. , 67. , 67. , 66.5, 70. , 69. , 68.5, 66. , 64.5,
       63. , 71. , 67. , 76. , 72. , 71. , 66. , 66

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder  # OneHotEncoder method to convert categorial data into numerical data)
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [13]:
from sklearn.model_selection import train_test_split  # Spliting the data for training and testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [14]:
x_train  # values of independent variables for training the model 

array([[0.0, 1.0, 72.0, 62.0],
       [1.0, 0.0, 70.5, 65.0],
       [0.0, 1.0, 70.5, 63.0],
       ...,
       [1.0, 0.0, 72.7, 69.0],
       [1.0, 0.0, 70.0, 69.0],
       [1.0, 0.0, 74.0, 62.0]], dtype=object)

In [15]:
y_train  # values of dependent variables for training the model

array([72. , 65. , 67. , 65. , 66. , 71. , 65.5, 63.5, 65. , 62.7, 65. ,
       71.5, 75. , 68. , 62.5, 68.7, 70. , 68. , 62. , 64.5, 70. , 63. ,
       69.5, 64.5, 62.3, 66.5, 70. , 62. , 63. , 68.2, 72. , 63. , 67. ,
       66. , 69. , 62. , 70. , 70.5, 67.5, 75. , 68. , 73. , 63. , 69.5,
       72. , 68. , 63. , 60. , 70.7, 68. , 68. , 63. , 68. , 66.7, 71. ,
       62.5, 65. , 65. , 69. , 63.2, 78. , 68.5, 68. , 71. , 62. , 64. ,
       70. , 65. , 73.2, 66.5, 69. , 62.5, 73. , 68.5, 64. , 73.2, 62.5,
       62. , 68. , 71.2, 65. , 67. , 66. , 66. , 66. , 67.7, 67. , 65. ,
       70. , 60. , 67.7, 66. , 60. , 63. , 66. , 64.5, 69. , 74. , 60. ,
       68. , 66. , 65. , 69. , 72. , 63. , 71.5, 64. , 64.7, 71. , 63. ,
       63. , 65.2, 62. , 72.7, 70.7, 69. , 63. , 63.5, 62. , 60. , 65.5,
       65.7, 63.5, 61. , 71.2, 63. , 69.5, 62. , 66.5, 66. , 65. , 65. ,
       70.5, 63. , 60. , 65.5, 70.5, 62.5, 64. , 62.5, 68.7, 68.5, 70.5,
       62. , 72. , 69. , 63. , 64. , 66.5, 62. , 61

In [16]:
from sklearn.linear_model import LinearRegression  # feeding the data to the machine model
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [17]:
y_est = regressor.predict(x_test)  #comparing the estimated values with the actual values
np.set_printoptions(precision=2)
print(np.concatenate((y_est.reshape(len(y_est),1), y_test.reshape(len(y_test),1)),1))

[[65.48 65.5 ]
 [69.07 71.5 ]
 [65.4  64.5 ]
 [62.47 63.5 ]
 [68.93 67.  ]
 [67.36 65.5 ]
 [68.44 70.  ]
 [64.42 62.5 ]
 [68.93 70.5 ]
 [63.23 61.5 ]
 [63.47 62.  ]
 [64.51 67.5 ]
 [63.23 64.  ]
 [68.68 69.  ]
 [68.39 69.5 ]
 [68.68 69.  ]
 [69.78 68.  ]
 [69.31 70.  ]
 [68.72 69.  ]
 [68.54 66.  ]
 [64.32 63.7 ]
 [65.32 67.5 ]
 [69.56 70.  ]
 [70.32 71.  ]
 [64.27 64.  ]
 [66.67 65.  ]
 [64.73 67.  ]
 [68.85 70.  ]
 [70.51 70.  ]
 [62.27 60.  ]
 [68.04 69.  ]
 [68.72 69.  ]
 [69.11 70.  ]
 [68.44 70.  ]
 [70.68 70.5 ]
 [69.77 68.  ]
 [69.81 68.5 ]
 [63.   63.5 ]
 [70.01 70.5 ]
 [64.04 63.5 ]
 [66.35 64.5 ]
 [67.05 66.  ]
 [68.68 71.  ]
 [62.47 62.5 ]
 [69.77 68.5 ]
 [64.68 62.  ]
 [67.84 67.2 ]
 [68.76 68.  ]
 [70.85 75.  ]
 [61.14 60.  ]
 [64.43 63.  ]
 [69.31 71.  ]
 [67.68 70.  ]
 [64.06 64.  ]
 [66.35 67.  ]
 [69.88 69.  ]
 [64.76 68.5 ]
 [68.44 68.  ]
 [71.56 71.  ]
 [64.76 67.5 ]
 [70.92 74.  ]
 [64.43 63.  ]
 [68.59 71.2 ]
 [70.08 69.  ]
 [70.03 67.  ]
 [69.24 67.  ]
 [63.28 57

In [18]:
y_est

array([65.48, 69.07, 65.4 , 62.47, 68.93, 67.36, 68.44, 64.42, 68.93,
       63.23, 63.47, 64.51, 63.23, 68.68, 68.39, 68.68, 69.78, 69.31,
       68.72, 68.54, 64.32, 65.32, 69.56, 70.32, 64.27, 66.67, 64.73,
       68.85, 70.51, 62.27, 68.04, 68.72, 69.11, 68.44, 70.68, 69.77,
       69.81, 63.  , 70.01, 64.04, 66.35, 67.05, 68.68, 62.47, 69.77,
       64.68, 67.84, 68.76, 70.85, 61.14, 64.43, 69.31, 67.68, 64.06,
       66.35, 69.88, 64.76, 68.44, 71.56, 64.76, 70.92, 64.43, 68.59,
       70.08, 70.03, 69.24, 63.28, 63.48, 64.71, 70.92, 70.53, 69.11,
       69.81, 64.51, 68.28, 68.69, 65.97, 69.24, 63.31, 64.11, 68.52,
       63.87, 66.84, 69.56, 69.64, 68.84, 64.6 , 64.11, 70.17, 66.47,
       65.44, 63.64, 68.44, 62.71, 68.44, 67.92, 68.44, 69.64, 63.63,
       67.15, 64.83, 65.97, 69.56, 69.77, 70.32, 65.16, 69.63, 70.61,
       64.72, 71.08, 63.56, 64.04, 64.83, 64.57, 69.79, 64.59, 64.28,
       64.6 , 65.31, 62.68, 63.88, 61.96, 70.04, 67.17, 71.08, 68.72,
       63.73, 65.71,

In [19]:
gender={'M':[0.0,1.0],'F':[1.0,0.0]}

In [ ]:
fatherht=int(input("Father's height(in inches)"))
motherht=int(input("Mother's height(in inches)"))
sex=str(input("Gender"))

In [ ]:
dataip=gender[sex]+[fatherht,motherht]

In [ ]:
result=regressor.predict([dataip])

In [ ]:
print(result)